=== canocmit/fish/nft/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Fish NFT Metadata",
  "type": "object",
  "required": ["name", "description", "image", "attributes"],
  "properties": {
    "name": { "type": "string" },
    "description": { "type": "string" },
    "image": { "type": "string" },
    "attributes": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["trait_type", "value"],
        "properties": {
          "trait_type": { "type": "string" },
          "value": {}
        }
      }
    }
  }
}

=== canocmit/fish/nft/metadata/9745.json
{
  "name": "Ranchu 9745_1",
  "description": "https://luckycoinvn.vercel.app",
  "image": "https://drive.google.com/uc?export=view&id=126I4GjZ-Ddo97eGNOkDMm_jzauFtfP8w",
  "attributes": [
    { "trait_type": "Rarity", "value": "Legendary" },
    { "trait_type": "Version", "value": "Genesis" }
  ]
}
